# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-03 17:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnic', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Choisissez un titre explicite (Soyez cr\xc3\xa9atif)', max_length=200, verbose_name=b'Nom de la recette *')),
                ('description', models.TextField(blank=True, help_text=b'Pas plus de 500 mots', null=True, verbose_name=b'Description')),
                ('prepare_time', models.DurationField(blank=True, help_text=b'hh:mm', null=True, verbose_name=b'Temps de pr\xc3\xa9paration')),
                ('cooking_time', models.DurationField(blank=True, help_text=b'hh:mm', null=True, verbose_name=b'Temps de cuisson')),
                ('total_time', models.DurationField(blank=True, null=True, verbose_name=b'Pr\xc3\xaat dans')),
                ('ingredient', ckeditor.fields.RichTextField(help_text=b'Utilisez les listes \xc3\xa0 puces (.) pour lister les ingr\xc3\xa9dients les uns au dessous des autres', verbose_name=b'Ingr\xc3\xa9dients *')),
                ('preparation', ckeditor.fields.RichTextField(help_text=b'Utilisez les listes num\xc3\xa9rot\xc3\xa9es  (1,2) pour d\xc3\xa9crire chaque \xc3\xa9tape', verbose_name=b'Instructions *')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'recipes', verbose_name=b'Image *')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=b'recipes', verbose_name=b'Autre image')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=b'recipes', verbose_name=b'Autre image')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=b'recipes', verbose_name=b'Autre image')),
                ('view', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Vue')),
                ('like', models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Like')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'Titre')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('view', models.IntegerField(blank=True, default=0, null=True)),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
