# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='modified_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='modified_at',
            new_name='update_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.Category'),
            preserve_default=False,
        ),
    ]
