# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20170607_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
