# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='timing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
