# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
    ]
