# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20170612_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
