# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 15:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20170613_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
