# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20170626_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
