# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20170706_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='timing',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prepare_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
