# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20180207_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='origin',
            field=models.ManyToManyField(blank=True, related_name='origin_video', to='recipe.Origin'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='origin',
            field=models.ManyToManyField(blank=True, related_name='recipe_origin', to='recipe.Origin'),
        ),
    ]
