# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-03 17:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'Titre')),
                ('text', ckeditor.fields.RichTextField(verbose_name=b'Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'blog')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, default=0, null=True)),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
