# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
