# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-03 17:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_contributor', models.BooleanField(default=True)),
                ('is_staff_member', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('sexe', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name=b'Biographie')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name=b'Pays de r\xc3\xa9sidence')),
                ('tel', models.CharField(blank=True, help_text='00228 00 00 00 00', max_length=50, verbose_name='T\xe9l\xe9phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'profiles')),
                ('linkedin', models.CharField(blank=True, help_text='https://fr.linkedin.com/Togokuizine', max_length=250, verbose_name='linkedin')),
                ('facebook', models.CharField(blank=True, help_text='https://www.facebook.com/Togokuizine', max_length=250, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, help_text='https://www.twitter.com/Togokuizine', max_length=250, verbose_name='Twitter')),
                ('gplus', models.CharField(blank=True, help_text='https://plus.google.com/+Togokuizine', max_length=250, verbose_name='Google plus')),
                ('instagram', models.CharField(blank=True, help_text='https://www.instagram.com/Togokuizine', max_length=250, verbose_name='Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]

