# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_contributor',
            field=models.BooleanField(default=True),
        ),
    ]
