# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gplus',
            field=models.CharField(blank=True, help_text='Google plus ID', max_length=50, verbose_name='Google plus'),
        ),
    ]
