# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170706_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.TextField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
