# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-25 17:31
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('insta_id', models.CharField(blank=True, max_length=50, null=True)),
                ('twit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lind_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('web_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site web')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants')),
                ('enabled', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='restaurant.Category', verbose_name='Catégorie')),
            ],
        ),
    ]
