# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180207_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='enabled',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
