# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170619_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
